"""fix_patient_constraint

Revision ID: 1d811683784b
Revises: d05337bc7b2d
Create Date: 2026-03-04 03:14:04.726346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d811683784b'
down_revision = 'd05337bc7b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('patient_patient_code_key'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('patient_patient_code_key'), ['patient_code'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
