"""initial schema - users, patients, sessions, audit_logs, treatment_plans, form_templates, patient_forms

Revision ID: b34a093c37d9
Revises: 
Create Date: 2026-03-03 17:05:32.555263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34a093c37d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=120), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permanently_locked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('form_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('allowed_roles', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('primary_diagnosis', sa.String(length=120), nullable=True),
    sa.Column('insurance', sa.String(length=120), nullable=True),
    sa.Column('ssn_last4', sa.String(length=4), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('pronouns', sa.String(length=30), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('ethnicity', sa.String(length=60), nullable=True),
    sa.Column('employment_status', sa.String(length=30), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=50), nullable=True),
    sa.Column('address_zip', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=60), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('referring_provider', sa.String(length=120), nullable=True),
    sa.Column('primary_care_physician', sa.String(length=120), nullable=True),
    sa.Column('pharmacy', sa.String(length=120), nullable=True),
    sa.Column('assigned_provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_provider_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_code')
    )
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_session_id'), ['session_id'], unique=True)

    op.create_table('patient_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filled_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['form_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_form', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_form_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_form_template_id'), ['template_id'], unique=False)

    op.create_table('treatment_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treatment_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_plan_patient_id'), ['patient_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_plan_patient_id'))

    op.drop_table('treatment_plan')
    with op.batch_alter_table('patient_form', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_form_template_id'))
        batch_op.drop_index(batch_op.f('ix_patient_form_patient_id'))

    op.drop_table('patient_form')
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_session_session_id'))

    op.drop_table('user_session')
    op.drop_table('patient')
    op.drop_table('form_template')
    op.drop_table('user')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
