"""add tenant model and tenant_id to all tables for multi-tenancy

Revision ID: d05337bc7b2d
Revises: b34a093c37d9
Create Date: 2026-03-03 18:40:58.955520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05337bc7b2d'
down_revision = 'b34a093c37d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_form_template_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_patient_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_tenant_patient_code', ['tenant_id', 'patient_code'])
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('patient_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_patient_form_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('treatment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_treatment_plan_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_tenant_username', ['tenant_id', 'username'])
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_session_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_session_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_tenant_username', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('treatment_plan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_treatment_plan_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('patient_form', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patient_form_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_tenant_patient_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_patient_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_form_template_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))
        batch_op.drop_column('tenant_id')

    op.drop_table('tenant')
    # ### end Alembic commands ###
